version: "3.8"

name: bigdnews

services:

  # bigdnews database
  bigdnews-mongo:
    container_name: bigdnews-mongo
    hostname: bigdnews-mongo
    networks:
      - bigdnews
    image: mongo
    restart: on-failure
    volumes:
      - ./database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u admin -p admin --quiet | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5m
      start_interval: 5s
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: BigDNews

  # bigdnews scraper
  bigdnews-scraper:
    container_name: bigdnews-scraper
    hostname: bigdnews-scraper
    networks:
      - bigdnews
    build:
      context: ./scraper
      dockerfile: Dockerfile
    image: bigdnews-scraper
    restart: on-failure
    depends_on:
      bigdnews-mongo:
        condition: service_healthy

volumes:
  mongo-data:
  mongo-configdb:

networks:
  bigdnews:




