version: "3.8"

name: bigdnews

services:

  # bigdnews database
  bigdnews-mongo:
    container_name: bigdnews-mongo
    hostname: bigdnews-mongo
    networks:
      - bigdnews
    image: mongo
    restart: on-failure
    volumes:
      - ./database/mongo/database.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh mongodb://$$DB_USER:$$DB_PWD@localhost:$$DB_PORT/?authSource=$$MONGO_INITDB_DATABASE --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 5s
    environment:
      DB_USER: bigdadmin
      DB_PWD: admin
      DB_PORT: 27017
      MONGO_INITDB_DATABASE: BigDNews
    command:
     - --auth

  bigdnews-service:
    container_name: bigdnews-service
    hostname: bigdnews-service
    networks:
      - bigdnews
    build:
      context: ./webservice
      dockerfile: Dockerfile
    image: bigdnews-service
    #volumes:
      #- ./service:/usr/app/
      #- /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      bigdnews-mongo:
        condition: service_healthy
    environment:
      PORT: 3000
      DATABASE_URL: mongodb://bigdadmin:admin@bigdnews-mongo:27017//?authSource=BigDNews

  # bigdnews scraper
  bigdnews-scraper:
    container_name: bigdnews-scraper
    hostname: bigdnews-scraper
    networks:
      - bigdnews
    build:
      context: ./scraper
      dockerfile: Dockerfile
    image: bigdnews-scraper
    restart: on-failure
    depends_on:
      bigdnews-mongo:
        condition: service_healthy
    environment:
      SERVICE_URL: bigdnews-service:3000
      API_URL: http://bigdnews-service:3000
      PLAYLIST_URL: https://youtube.com/playlist?list=PL2QF6_2vxWih_qskqy_t_axr0CtbWJXxh&si=QOl4T_2VQ4xXRCUi

  restarter:
    image: docker:cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bin/sh", "-c", "while true; do sleep 3600; if [ $(docker inspect -f '{{.State.Running}}' bigdnews-scraper) = \"false\" ]; then docker restart bigdnews-scraper; else echo scraper still running; fi done"]
    restart: unless-stopped


volumes:
  mongo-data:
  mongo-configdb:

networks:
  bigdnews:




